language: python

python:
    - 3.5

env:
    global:
        - export DJANGO_SETTINGS_MODULE="Vango.settings"
        - export PYTHONPATH=$HOME/builds/LopsanAMO/Vangoghstagram
        - export PIP_USE_MIRRORS=true

install:
    - pip install -r requerimientos.txt

after_success:
- pip freeze

notifications:
  email:
    on_success: change
    on_failure: always
