# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 07:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vangouser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('profile_picture', models.CharField(blank=True, max_length=100)),
                ('followed_by', models.CharField(blank=True, max_length=100)),
                ('media', models.CharField(blank=True, max_length=100)),
                ('follows', models.CharField(blank=True, max_length=100)),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Informacion extra',
                'verbose_name_plural': 'Informacion extra',
            },
        ),
    ]
